version: '3'

volumes:
  keycloak-db-data:
  admin-db-data:
  pgadmin-data:
  audit-log-data:
  notification-db-data:
  core-db-data:

services:
  keycloak-db:
    image: postgres
    container_name: keycloak-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin           # Keycloak admin username
      KEYCLOAK_ADMIN_PASSWORD: admin # Keycloak admin password
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
    ports:
      - 8088:8080
    depends_on:
      - keycloak-db
  admin-service-db:
    image: postgres
    container_name: admin-service-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: admin-db
      POSTGRES_USER: abbes
      POSTGRES_PASSWORD: abbes
    volumes:
      - admin-db-data:/var/lib/postgresql/data
  notification-service-db:
    image: postgres
    container_name: notification-service-db
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: notification-db
      POSTGRES_USER: abbes
      POSTGRES_PASSWORD: abbes
    volumes:
      - notification-db-data:/var/lib/postgresql/data
  core-service-db:
    image: postgres
    container_name: core-service-db
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: core-db
      POSTGRES_USER: abbes
      POSTGRES_PASSWORD: abbes
    volumes:
      - core-db-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: abbes@kyrios.dz
      PGADMIN_DEFAULT_PASSWORD: abbes
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  audit-log-db:
    image: mongo
    container_name: audit-log-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: abbes
      MONGO_INITDB_ROOT_PASSWORD: abbes
      MONGO_INITDB_DATABASE: audit-log-db
    volumes:
      - audit-log-data:/data/db
    ports:
      - "27017:27017"
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8383:8080"