spring:
  application:
    name: core
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8088/realms/erp-dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/core-db
    username: abbes
    password: abbes
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

permission-service:
  uri: http://localhost:8080/admin-service/api/v1/permission
  authority-param-name: authority
  module-param-name: module
  module-name: core-service